global using Azure.Messaging.ServiceBus;
global using Azure.Messaging.ServiceBus.Administration;
global using EventBus;
global using EventBus.Contracts;
global using EventBus.Events;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Text;
global using System.Text.Json;